
service: serverless-chat-app


provider:
  name: aws
  runtime: python3.7
  iamRoleStatements:
        - Effect: Allow
          Action:
              - "dynamodb:PutItem"
              - "dynamodb:GetItem"
              - "dynamodb:UpdateItem"
              - "dynamodb:DeleteItem"
              - "dynamodb:BatchGetItem"
              - "dynamodb:BatchWriteItem"
              - "dynamodb:Scan"
              - "dynamodb:Query"
          Resource:
              - "arn:aws:dynamodb:us-east-1:*:*"

plugins:
  - serverless-python-requirements
custom:
    pythonRequirements:
        dockerizePip: non-linux
        noDeploy: []


functions:
  ping:
    handler: handler.ping
    events:
       - http:
           path: ping
           method: get
